name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Fitur Baru'
    labels:
      - 'feature'
  - title: '✨ Pembaruan'
    labels:
      - 'enhancement'
  - title: '🐛 Perbaikan'
    labels:
      - 'bug'
  - title: '📃 Dokumentasi'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🖥️ Situs'
    labels:
      - 'site'
  - title: '📎 Github'
    labels:
      - 'github'
exclude-labels:
  - 'ask'

change-template: '- (#$NUMBER) | $TITLE @$AUTHOR'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Perubahan
  $CHANGES

  ## Daftar Kontributor
  $CONTRIBUTORS
