# Site Setting
title: hidrokit
description: analisis hidrologi dengan python

# Local Setting
baseurl: ""
url: ""

# Theme
theme: "just-the-docs"
# remote_theme: pmarsceill/just-the-docs

# Theme settings
# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Enable or disable the site search
# Use this command to update index: bundle exec just-the-docs rake search:init
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/taruma/hidrokit"
