name: hidrokit-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10 
  # core
  - matplotlib=3.8.0
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.0
  - xlrd=2.0.1
  # conda environment
  - ipykernel=6.28.0 
  - spyder-kernels=2.5.0
  - twine=4.0.2
  # testing dependencies
  - pytest=7.4.0 
  - pytest-cov=3.10.14
  - coverage=7.2.2
  # vscode settings
  - flake8=7.0.0 
  - autopep8=2.0.4
  - pylint=2.16.2
  # sphinx settings
  - sphinx=5.0.2 
  - numpydoc=1.5.0  
