name: Jekyll Build
on: 
  push:
    branches:
      - gh-pages
  pull_request:
    type: [opened, reopened, synchronize]
    branches:
      - gh-pages

jobs:
  jekyll_build:
    runs-on: ubuntu-latest
    # env:
    #   BUNDLE_GEMFILE: ${{ github.workspace }}/docs/Gemfile
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # - run: bundle exec htmlproofer _site --assume-extension --disable-external
    - run: bundle exec jekyll build -s . -d _site --config _config_local.yml
